//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUL
    {
        public System.Guid Id { get; set; }
        public string Zone_Code { get; set; }
        public string Zone_Description { get; set; }
        public string NSN { get; set; }
        public string Item_Name { get; set; }
        public string Trade_Name { get; set; }
        public string Manufacturer_Part_Number { get; set; }
        public string Product_MSDS_Number { get; set; }
        public string MSDS_Prep_Date { get; set; }
        public string Authorization_Expiration_Date { get; set; }
        public string Update_Date { get; set; }
        public string Active { get; set; }
        public string CAGE_Code { get; set; }
        public string Updated_By { get; set; }
        public string Building_Code { get; set; }
        public string Update_Date_2 { get; set; }
        public string Unit_of_Issue { get; set; }
        public string Specification_Number { get; set; }
        public string Specification_Type_Grade_Class { get; set; }
    }
}
