//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV
    {
        public System.Guid Id { get; set; }
        public string CAGE_Code { get; set; }
        public string Create_Date { get; set; }
        public string Create_Username { get; set; }
        public string Disposal_Code { get; set; }
        public string Hazard_Code { get; set; }
        public string UoM { get; set; }
        public string Memo { get; set; }
        public string Document_Number_Code { get; set; }
        public string Expiration_Date { get; set; }
        public string Unit_Price { get; set; }
        public string Lot_Batch_Number { get; set; }
        public string Original_Expiration_Date { get; set; }
        public string Original_Quantity { get; set; }
        public string Original_UoM { get; set; }
        public string Product_State_Code { get; set; }
        public string Quantity { get; set; }
        public string Status { get; set; }
        public string Unit_of_Issue { get; set; }
        public string Issue_Point_Code { get; set; }
        public string Item_Name { get; set; }
        public string Kit_Description { get; set; }
        public string Kit_ID_Code { get; set; }
        public string Kit_Indicator { get; set; }
        public string PNI { get; set; }
        public string Kit_Price { get; set; }
        public string Manufacturer_Kit_Indicator { get; set; }
        public string Manufacturer_Name { get; set; }
        public string Manufacturer_Part_Number { get; set; }
        public string NSN { get; set; }
        public string Product_MSDS_Number { get; set; }
        public string Original_Issuepoint_Code { get; set; }
        public string Separable { get; set; }
        public string Serial_Number { get; set; }
        public string Shelf_Bin { get; set; }
        public string Trade_Name { get; set; }
        public string Update_Date { get; set; }
        public string Updated_By { get; set; }
        public string Zone_Code { get; set; }
        public string Shelf_Life_Code { get; set; }
        public string Kgrams_QTY { get; set; }
        public string Original_Kgrams_QTY { get; set; }
    }
}
