//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISU
    {
        public System.Guid Id { get; set; }
        public string Unit_Price { get; set; }
        public string Issue_Point_Code { get; set; }
        public string Date_Out { get; set; }
        public string NSN { get; set; }
        public string Building_Code { get; set; }
        public string Hazard_Code { get; set; }
        public string Issue_Group_Sequence { get; set; }
        public string Issue_QTY_Out { get; set; }
        public string Scale_Indicator { get; set; }
        public string UoM { get; set; }
        public string Item_Name { get; set; }
        public string Memo_Note { get; set; }
        public string Job_ID_Code { get; set; }
        public string Weight_Out { get; set; }
        public string Kit_Indicator { get; set; }
        public string Pounds_Out_QTY { get; set; }
        public string Supervisor_Code { get; set; }
        public string MSDS_Printed_IND { get; set; }
        public string Serial_Number { get; set; }
        public string Organization_Code { get; set; }
        public string Product_MSDS_Number { get; set; }
        public string ID_Number { get; set; }
        public string Resource_Name { get; set; }
        public string Status_Out { get; set; }
        public string Trade_Name { get; set; }
        public string Update_Date { get; set; }
        public string Updated_By { get; set; }
        public string Zone_Code { get; set; }
        public string Resource_Out_Cd { get; set; }
    }
}
