//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class MXQ
    {
        public System.Guid Id { get; set; }
        public string Zone_Code { get; set; }
        public string Zone_Description { get; set; }
        public string NSN { get; set; }
        public string Building_Code { get; set; }
        public string Trade_Name { get; set; }
        public string Item_Name { get; set; }
        public string Update_Date { get; set; }
        public string ZQL { get; set; }
    }
}
