//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOP
    {
        public System.Guid Id { get; set; }
        public string Backorder_Indicator { get; set; }
        public string CAGE_Code { get; set; }
        public string Credit_Card_Code { get; set; }
        public string Delivery_Destination { get; set; }
        public string Document_Date { get; set; }
        public string Document_Serial_Number { get; set; }
        public string Issue_Exception_Code { get; set; }
        public string Issue_Point_Code { get; set; }
        public string Job_Order_Code { get; set; }
        public string Job_Order_Number { get; set; }
        public string JOCAS_Number { get; set; }
        public string Manufacturer_Serial_Number { get; set; }
        public string NSN { get; set; }
        public string Order_Activity { get; set; }
        public string Order_Command_Code { get; set; }
        public string Order_Comments { get; set; }
        public string Order_Completion_Date { get; set; }
        public string Order_Demand_Code { get; set; }
        public string Order_Document_Number { get; set; }
        public string Order_Fund_Code { get; set; }
        public string Order_Priority { get; set; }
        public string Order_QTY { get; set; }
        public string Date_Ordered { get; set; }
        public string Order_Request_Number { get; set; }
        public string Order_Shop_Code { get; set; }
        public string Order_Unit_of_Issue { get; set; }
        public string Order_Urgency { get; set; }
        public string Projected_Delivery_Code { get; set; }
        public string Projected_Delivery_Date { get; set; }
        public string Request_Delete_Date { get; set; }
        public string Request_Status_Code { get; set; }
        public string Requisistion_Transaction_Status_Code { get; set; }
        public string Distribution_Code { get; set; }
        public string Workorder_Number_Ship_To { get; set; }
        public string Ship_to_Location { get; set; }
        public string SRD { get; set; }
        public string Transaction_Exception_Code { get; set; }
        public string To_Supply_Date { get; set; }
        public string TRIC { get; set; }
        public string UJC { get; set; }
        public string Update_Date { get; set; }
        public string Updated_By { get; set; }
        public string Serial_Number_Count { get; set; }
        public string Requester_Logon { get; set; }
        public string Work_Order_Code { get; set; }
        public string Work_Unit_Code { get; set; }
        public string Zone_Code { get; set; }
    }
}
