//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class QOH
    {
        public System.Guid Id { get; set; }
        public string Issue_Point_Code { get; set; }
        public string NSN { get; set; }
        public string Serial_Number { get; set; }
        public string Status { get; set; }
    }
}
