//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMMSReadEmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN
    {
        public System.Guid Id { get; set; }
        public string Received_Date { get; set; }
        public string Transfer_Date { get; set; }
        public string Transfer_From_Issue_Point { get; set; }
        public string Receiving_Issue_Point { get; set; }
        public string Serial_Number { get; set; }
        public string Transfer_User_Logon { get; set; }
        public string Received_User_Logon { get; set; }
    }
}
